Phase08 authentication
Star-Academy/Summer1401-FE-Team03 pull request #2
Opened 2022-07-26 18:57 UTC by AtaReversei

2022-07-27 02:57 UTC, SinaMAmini commented on src/app/components/footer/footer.component.scss
> +:host {
بیشتر  شنیدم که میگن از :host استفاده نکنیم بهتره مگر اینکه مجبور شیم... ولی من که دیدم همه رو تو hostگذاشتین... من نمیدونم شاید بعداً منتور ها گیر بدن...

2022-07-27 03:07 UTC, SinaMAmini commented on src/styles.scss
> +        .ngxp__container {
برا اینکه stylelint رو disable نکنید؛ میشه از BEM استفاده کرد که البته بنظرم فرقی نداره

2022-07-27 03:08 UTC, SinaMAmini commented on src/app/components/footer/footer.component.scss
> +    margin-block-start: auto;
استفاده از margin هم مثه host ، ممکنه خیلی خوب نباشه

2022-07-27 03:45 UTC, SinaMAmini commented on src/app/pages/profile/profile.component.html
> +<p>profile works!</p>
به نظرم صفحه پروفایل خالی قابل قبول نباشه...
گفته بودن یه button برای خروج بذاریم تو پروفایل

2022-07-27 03:52 UTC, SinaMAmini commented on src/app/utils/api.utils.ts
> +export const API_USER_ONE = BASE_URL + '/user/one';
به نظرم از این که استفاده نمیشه؛ میشه دلیتش کرد

2022-07-27 03:52 UTC, SinaMAmini requested changes
خیلی کد خوبی بود به نظرم خسته نباشید

2022-07-27 05:25 UTC, dorrin-sot requested changes

2022-07-27 05:25 UTC, dorrin-sot commented on src/app/models/api-error.model.ts
> +interface ApiError {
میتونه کلمه export قبل interface باشه و خط ۶ حذف شه

2022-07-27 05:25 UTC, dorrin-sot commented on src/app/pages/auth/auth.component.ts
> +        this.isLoginInView = !this.isLoginInView;
مقادیر موجود در this.user رو اینجا خالی کنین که وقتی نوع فرم تغییر کرد اطلاعات قبلی نمانده باشند

2022-07-27 05:25 UTC, dorrin-sot commented on src/app/pages/auth/auth.component.html
> +
بهتره اینجا برای فرم ثبت نام یک فیلد هم برای "تکرار رمز عبور" قرار بدین که احیانا کاربر رمز خود را اشتباه تایپ نکرده باشد. همچنین در متد formSubmitHandler() قبل ارسال درخواست رجیستر هم چک کنید که این دو برابر باشند

2022-07-27 05:25 UTC, dorrin-sot commented on src/app/pages/auth/auth.component.html
> +    <button class="primary" type="submit">ورود</button>
برای استرینگ داخل این دکمه شرط isLoginInView بگذارید (مثل تیتر فرم)

2022-07-27 05:25 UTC, dorrin-sot commented on src/app/pages/auth/auth.component.ts
> +    public isLoginInView: boolean = true;
یه حالت nitpic ریز😅: isInLoginView باشه

2022-07-27 05:25 UTC, dorrin-sot commented on src/app/utils/api.utils.ts
> +export const API_USER_AUTH = BASE_URL + '/user/auth';
اگه از Template string برای اینها استفاده کنین خوشگل‌تره

2022-07-27 06:00 UTC, AtaReversei commented on src/app/components/footer/footer.component.scss
> +    margin-block-start: auto;
واسه این مورد مجبور بودیم از margin استفاده کنیم تا footer رو بندازیم پایین

2022-07-27 06:01 UTC, AtaReversei commented on src/app/pages/profile/profile.component.html
> +<p>profile works!</p>
درسته اضافه میکنیم حتما

2022-07-27 06:01 UTC, AtaReversei commented on src/app/models/api-error.model.ts
> +interface ApiError {
درسته

2022-07-27 06:19 UTC, dibaaamir requested changes

2022-07-27 06:19 UTC, dibaaamir commented on src/app/components/header/header.component.scss
> +    width: max-content;
inline-size

2022-07-27 06:19 UTC, dibaaamir commented on src/app/components/header/header.component.scss
> +    min-width: 28rem;
min-inline-size

2022-07-27 06:19 UTC, dibaaamir commented on src/app/pages/auth/auth.component.html
> +        <input type="email" name="email" [(ngModel)]="user.email" />
بهتر نیست توی لاگین یا فقط کاربری باشه یا فقط ایمیل؟ فکر نمیکنم کاربر حال داشته باشه هر دو رو بزنه. اگر میخواین امکان هردوش باشه میتونین جدا کنین و انتخاب بزارین که با چی وارد بشه.

2022-07-27 06:19 UTC, dibaaamir commented on src/app/pages/auth/auth.component.html
> +        نام کاربری:
ممکنه کاربر اول بخواد ثبت نام کنه و بعد مثلا یادش بیاد که داره حساب کاربری. وقتی باتن میخوام وارد بشم رو زد اینپوت ها ور خالی کنین

2022-07-27 06:19 UTC, dibaaamir commented on src/app/pages/auth/auth.component.html
> +<form (submit)="formSubmitHandler()">
اگر یکم فاصله رو از بالا کم کنین تا کاربر برای دیدن کل فرم نخواد اسکرول کنه

2022-07-27 06:19 UTC, dibaaamir commented on src/app/pages/auth/auth.component.html
> +<form (submit)="formSubmitHandler()">
منظورم کل فرمه

2022-07-27 06:49 UTC, Negarnbkhti42 commented on src/app/services/api/auth/auth.service.ts
> +import {Login} from '../../../models/login.model';
importها میتونن به صورت absolute باشن

2022-07-27 06:55 UTC, Negarnbkhti42 commented on src/app/components/header/header.component.scss
> +        grid-template-columns: 1.5em 1fr auto;
اینجا لزومی هست که از em استفاده شده؟

2022-07-27 07:05 UTC, AtaReversei commented on src/app/components/footer/footer.component.scss
> +:host {
درسته، ممکنه کانفلیکت بده ولی بعضی وقت ها هم برای اینکه یک تگ رپر نیاریم و تگ معنادار رو خراب نکنیم از این کارا میکنیم

2022-07-27 07:21 UTC, Negarnbkhti42 commented on src/app/components/snackbar/snackbar.component.ts
> +        if (this.timeout) {
برای این قسمت هم میتونید تابع clearTimeoutIfExists رو فراخوانی کنید

2022-07-27 07:38 UTC, Negarnbkhti42 commented on src/styles.scss
> +    popper-content {
این روش سلکت کردن ماژول‌ها بعد از کامئایل برنامه میتونه ایجاد مشکل کنه

2022-07-27 07:40 UTC, AtaReversei commented on src/app/pages/auth/auth.component.html
> +<form (submit)="formSubmitHandler()">
حل شد

2022-07-27 07:41 UTC, AtaReversei commented on src/app/pages/auth/auth.component.html
> +        نام کاربری:
به نظر من وقتی برعکسش اتفاق بیفته خیلی راحتتر میشه واسه کاربر و فقط اسمشو وارد میکنه و یه حساب کاربری درست میکنه

2022-07-27 07:42 UTC, HessamCheraghi requested changes

2022-07-27 07:42 UTC, HessamCheraghi commented on src/app/components/snackbar/snackbar.component.html
> +
اینجا یه اینتر اضافیه

2022-07-27 07:42 UTC, HessamCheraghi commented on src/styles.scss
> +        /* stylelint-enable selector-class-pattern */
این جا چیز خاصی میخواستید اضافه کنید؟ اگه فقط برای این فایل هست بهتره بالای فایل باشه

2022-07-27 07:42 UTC, AtaReversei commented on src/app/components/header/header.component.scss
> +    min-width: 28rem;
اعمال شد

2022-07-27 07:43 UTC, AtaReversei commented on src/app/components/header/header.component.scss
> +    width: max-content;
اعمال شد

2022-07-27 07:44 UTC, AtaReversei commented on src/app/components/header/header.component.html
> +        <button class="auth-button" [popper]="popperContent" [popperPlacement]="NgxPopperjsPlacements.BOTTOMSTART">
بله رویه CI/CD ایراد داشت، الان میتونید ببینید

2022-07-27 07:46 UTC, AtaReversei commented on src/app/utils/api.utils.ts
> +export const API_USER_AUTH = BASE_URL + '/user/auth';
اعمال شد

2022-07-27 07:47 UTC, AtaReversei commented on src/app/pages/auth/auth.component.ts
> +    public isLoginInView: boolean = true;
این به نظرم isLoginInView به معنی آیا لاگین تو دیدمون هست بهتره تا isInLoginView آیا داخل لاگین ویو هستیم

2022-07-27 07:48 UTC, AtaReversei commented on src/app/pages/auth/auth.component.html
> +    <button class="primary" type="submit">ورود</button>
حل شد

2022-07-27 07:50 UTC, AtaReversei commented on src/app/pages/auth/auth.component.html
> +
بعضی سایت ها الان فقط یکبار از کاربر رمز رو میگیرن، و چون کاربر ایمیلش رو داره میتونه رمز رو بازیابی کنی یا عوض کنه
حرف شما هم درسته، تو تغییرات بعدی شاید اضافش کردیم

2022-07-27 07:57 UTC, AtaReversei commented on src/app/models/api-error.model.ts
> +interface ApiError {
اعمال شد

2022-07-27 08:00 UTC, AtaReversei commented on src/app/pages/auth/auth.component.ts
> +        this.isLoginInView = !this.isLoginInView;
خانم شفیعی: ممکنه کاربر اول بخواد ثبت نام کنه و بعد مثلا یادش بیاد که داره حساب کاربری. وقتی باتن میخوام وارد بشم رو زد اینپوت ها ور خالی کنین

من: به نظر من وقتی برعکسش اتفاق بیفته خیلی راحتتر میشه واسه کاربر و فقط اسمشو وارد میکنه و یه حساب کاربری درست میکنه

2022-07-27 08:02 UTC, AtaReversei commented on src/app/pages/auth/auth.component.html
> +        <input type="email" name="email" [(ngModel)]="user.email" />
تو تغییرات بعدی اضافه میکنیم

2022-07-27 08:04 UTC, dibaaamir approved these changes

2022-07-27 08:04 UTC, AtaReversei commented on src/app/components/header/header.component.scss
> +        grid-template-columns: 1.5em 1fr auto;
اشتباه شده، اصلاح شد

2022-07-27 08:06 UTC, AtaReversei commented on src/app/components/snackbar/snackbar.component.ts
> +        if (this.timeout) {
اصلاح شد

2022-07-27 08:11 UTC, Alirezab-2000 commented on src/app/components/snackbar/snackbar.component.html
> +
خودمون زدیم برای جداسازی اجزای مختلف. به توصیه منتورمون

2022-07-27 08:12 UTC, dorrin-sot approved these changes
زیبا :) خسته نباشید!

2022-07-27 08:12 UTC, Alirezab-2000 commented on src/styles.scss
> +        /* stylelint-enable selector-class-pattern */
برای اینکه style lint گیرنده به این بخش استایل ها کامنتا رو گذاشتیم. فقط برای این قسمته برای کل فایل نیست

2022-07-27 08:21 UTC, HessamCheraghi approved these changes

2022-07-27 08:21 UTC, Negarnbkhti42 commented on src/app/components/footer/footer.component.scss
> +        width: 100%;
logical

2022-07-27 09:06 UTC, msrazavi requested changes

2022-07-27 09:06 UTC, msrazavi commented on src/app/components/footer/footer.component.scss
> +            max-width: 20rem;
logical

2022-07-27 09:06 UTC, msrazavi commented on src/app/components/snackbar/snackbar.component.scss
> +    p {
بهتره کلاس بدید

2022-07-27 09:06 UTC, msrazavi commented on src/app/components/header/header.component.html
> +            <i class="far fa-user icon"></i>
در عرض کم مرورگر دکمه کاربر نمایش داده نمی‌شود.
![image](https://user-images.githubusercontent.com/24840082/181208184-45ecdf3a-1dc6-41c1-ad6e-fa209937f860.png)

2022-07-27 10:12 UTC, Alirezab-2000 submitted a review, later dismissed

2022-07-27 10:16 UTC, Alirezab-2000 commented on src/app/pages/profile/profile.component.html
> +<p>profile works!</p>
بله درست میفرمایید

2022-07-27 10:18 UTC, Alirezab-2000 commented on src/app/components/footer/footer.component.scss
> +        width: 100%;
حل شد

2022-07-27 10:20 UTC, Alirezab-2000 commented on src/app/components/snackbar/snackbar.component.scss
> +    p {
به نظرم اینجا چون راحت با این میشه این تگ رو سلکت کرد، کلاس ندیم بهتره

2022-07-27 10:21 UTC, Alirezab-2000 commented on src/app/components/header/header.component.html
> +            <i class="far fa-user icon"></i>
بله این مورد هم درست میکنیم در ادامه

2022-07-27 10:25 UTC, ParsaArvanehPA requested changes

2022-07-27 10:25 UTC, ParsaArvanehPA commented on src/app/components/snackbar/snackbar.component.ts
> +    }
ی متد private بسازید به resetSnackBarProperties و توش بیاید اون 3 تا چیزی که داره رو null یا false کنید. بعد همونو تو خط 29-31 و 37-39 و 44 فراخوانی کنید

2022-07-27 10:25 UTC, ParsaArvanehPA commented on src/app/components/snackbar/snackbar.component.ts
> +        this.clearTimeoutIfExists();
insert new line end of 23

2022-07-27 10:25 UTC, ParsaArvanehPA commented on src/app/components/snackbar/snackbar.component.ts
> +        this.clearTimeoutIfExists();
insert new line end of 36

2022-07-27 10:25 UTC, ParsaArvanehPA commented on src/app/components/snackbar/snackbar.component.ts
> +    }
ن، فقط فک کنم تو 44 بزارید بسه، بقیه پاک شن( خودتون چک کنید خراب نشه...)

2022-07-27 10:25 UTC, ParsaArvanehPA commented on src/app/components/snackbar/snackbar.component.ts
> +        this.SnackbarService.initComponent(this);
ها؟
چرا واقعا؟ 
اون متد show ای که الان دارید کلا باید بره تو service. 
همه اون چیزائی هم کگه بهشون نیاز دار بره اونجه، بعد اونطوری که دیشب بهتون یاد دادم تو html ئش آدرس بدید به msg , isShown, type بشه. کلا هرچی الان تو سرویسش هست رو باید پاک کنید.
عجیبه طرز هندل کردنتون. دارید کلا کامپوننت رو میدید به یارو!

2022-07-27 10:25 UTC, ParsaArvanehPA commented on src/app/app.module.ts
> +        NgxPopperjsModule,
راجع به خط 17 پایین تر گفتم ی چیزی بهتون

2022-07-27 10:25 UTC, ParsaArvanehPA commented on src/app/components/header/header.component.html
> +            <i class="far fa-user icon"></i>
فایله رو بشکونید. خیلی بلند شده
مثلا اون 3 4 تا دکمه چپ بشن ی کامپوننت، اون راستی ها بشن یدونه دیگه

2022-07-27 10:25 UTC, ParsaArvanehPA commented on src/app/components/header/header.component.scss
> +}
همیشه @mdeia رو آخر فایلا میزارن. بیارین این تیکه رو بالای اون

2022-07-27 10:25 UTC, ParsaArvanehPA commented on src/app/components/snackbar/snackbar.component.spec.ts
> +
del empty line

2022-07-27 10:25 UTC, ParsaArvanehPA commented on src/app/guard/auth.guard.spec.ts
> +
del empty line

2022-07-27 10:25 UTC, ParsaArvanehPA commented on src/app/models/api/login.model.ts
> +}
inset new line

2022-07-27 10:25 UTC, ParsaArvanehPA commented on src/app/models/api/register.model.ts
> +}
ne wline

2022-07-27 10:25 UTC, ParsaArvanehPA commented on src/app/services/snackbar/snackbar.service.spec.ts
> +
empty line

2022-07-27 10:27 UTC, Alirezab-2000 commented on src/app/services/api/auth/auth.service.ts
> +import {Login} from '../../../models/login.model';
بله این رو در ادامه درست میکنیم

2022-07-27 10:28 UTC, Negarnbkhti42 approved these changes

2022-07-27 10:28 UTC, msrazavi approved these changes

2022-07-27 10:30 UTC, AtaReversei commented on src/app/pages/auth/auth.component.html
> +        <input type="text" name="firstName" [(ngModel)]="user.firstName" placeholder="امیر" />
معمولا مثال میذارنا، از اینا گذاشتیم، لیبل برای موضوع و placeholder برای نمونه

2022-07-27 10:31 UTC, Alirezab-2000 commented on src/app/app.component.ts
> +        this.checkIsLogin().then();
حل شد

2022-07-27 10:33 UTC, Alirezab-2000 commented on src/app/app.component.ts
> +    }
زدم

2022-07-27 10:34 UTC, AliZoghi commented on src/app/utils/api.utils.ts
> +export const API_USER_ONE = `${BASE_URL}/user/one`;
فکر نمیکنم جایی استفاده شده باشه

2022-07-27 10:36 UTC, Alirezab-2000 commented on src/app/components/header/header.module.ts
> +    imports: [CommonModule, SearchBoxModule, NgxPopperjsModule, DividerVerticalModule, RouterModule],
حل شد

2022-07-27 11:55 UTC, Alirezab-2000 commented on src/app/services/api/api.service.ts
> +        showSnackbarOnFail = true
اینا همینجا استفاده میشه فقط، دیگه مدل فکر نکنم لازم باشه

2022-07-27 11:57 UTC, Alirezab-2000 commented on src/app/services/api/api.service.ts
> +    public async post<T>(
این ممکنه response های متفاوت از جنس های متفاوت بخواد به ما برگردونه. برای همین نمیشه از یه مدل واحد استفاده کرد. و اینکه میخوایم وقتی response برمیگرده از همون جنسی باشه که ما به عنوان response تعیین کردیم

2022-07-27 11:59 UTC, Alirezab-2000 commented on src/app/services/api/api.service.ts
> +        if (showSnackbarOnFail) this.SnackbarService.show((data as ApiError).message, SnackbarTypes.Error);
متوجه منظورت نمیشیم

2022-07-27 12:00 UTC, Alirezab-2000 commented on src/app/utils/api.utils.ts
> +
این base url به نظرم با یه اینتر از بقیه جدا باشه بهتره

2022-07-27 12:02 UTC, Alirezab-2000 commented on src/styles.scss
> +        /* stylelint-disable selector-class-pattern */
این اسم کلاس ها ngx و اینا، حالت kebab case نیست، استایل لینت بهشون گیر میده. بعد اسم این کلاسا رو هم نمیتونیم عوض کنیم چون مال popper js هست

2022-07-27 12:04 UTC, Alirezab-2000 commented on src/app/app.component.html
> +<app-snackbar></app-snackbar>
حل شد

2022-07-27 12:18 UTC, Alirezab-2000 commented on src/app/components/snackbar/snackbar.component.ts
> +    }
حل شد

2022-07-27 12:29 UTC, Alirezab-2000 commented on src/app/components/snackbar/snackbar.component.ts
> +        this.SnackbarService.initComponent(this);
حل شد

2022-07-27 12:29 UTC, ArefHbb reviewed
خسته نباشید خیلی خوب بود

2022-07-27 12:29 UTC, ArefHbb commented on src/app/app.component.html
چرا enter?

2022-07-27 14:46 UTC, SinaMAmini approved these changes

2022-07-27 15:57 UTC, Alirezab-2000 commented on src/app/services/api/api.service.ts
> +        showSnackbarOnFail = true
بیژن گفت هفته بعد میگم اینا رو. قبلش میخواد یه چیزی بگه

2022-07-27 21:16 UTC, ParsaArvanehPA requested changes

2022-07-27 21:16 UTC, ParsaArvanehPA commented on src/app/pages/auth/login/language/message.ts
> +export const YOU_ARE_LOGGED_IN = 'شما وارد حساب کاربری خود شدید!';
تو فولدر پدرش، یعنی auth یه فولدر language بسازید. یدونه از اینا هم اونجا باشه. 
اسمش هم واحد باشه. الان اینا message هستن، بعدا ک نیستن. ی اسمی بزارید که جامع تر باشه.

2022-07-27 21:16 UTC, ParsaArvanehPA commented on src/app/pages/auth/login/language/message.ts
> +export const YOU_ARE_LOGGED_IN = 'شما وارد حساب کاربری خود شدید!';
اسم خود ورییبل ئه نامناسبه

2022-07-27 21:16 UTC, ParsaArvanehPA commented on src/app/pages/home/slideshow/slideshow.component.spec.ts
> -});
چرا پاک شده؟

2022-07-27 21:16 UTC, ParsaArvanehPA commented on src/app/services/api/api.service.ts
> +        if (showSnackbarOnFail) this.SnackbarService.show((data as ApiError).message, SnackbarTypes.Error);
زنگ بزنید

2022-07-27 21:16 UTC, ParsaArvanehPA commented on src/app/services/api/auth/auth.service.ts
> +        console.log('here');
del log

2022-07-27 21:16 UTC, ParsaArvanehPA commented on src/app/models/api/login.model.ts
> +}
2 تا فایل مختلف باشه تمیز تر و قشنگ تره

2022-07-27 21:16 UTC, ParsaArvanehPA commented on src/app/models/api/register.model.ts
> +}
2 تا فیال بشه

2022-07-27 21:16 UTC, ParsaArvanehPA commented on src/app/pages/home/slideshow/slideshow.component.spec.ts
> -});
این که این تستائی که پاک کردید رو برگردونید یا نه رو با بیژن هماهنگ کنید.
الان سرفصلا یادم نیستن، احتمالا کارما هم یاد میده. باشن بهتره. اگر تو ci cd خطا میخوردی زنگ بزنید ولی سعی کنید اون 1 دونه تست دیفالت رو نگه دارید.

2022-07-28 07:03 UTC, Alirezab-2000 commented on src/app/components/header/search-box/search-box.component.spec.ts
> -});
داخل describe رو فقط پاک کردیم. هستش فایله

2022-07-28 07:10 UTC, Alirezab-2000 commented on src/app/pages/auth/login/language/message.ts
> +export const YOU_ARE_LOGGED_IN = 'شما وارد حساب کاربری خود شدید!';
فولدر هاش رو جابجا کردیم. ولی درمورد اسمش به نظرم همینجور بمونه بعدا نهایتن تغییرش میدیم. چون زیاد با کارکردش اشنا نیستیم بعد که بیشتر یادگرفتیم بهتر میتونیم عمل کنیم

2022-07-28 07:13 UTC, Alirezab-2000 commented on src/app/pages/auth/login/language/message.ts
> +export const YOU_ARE_LOGGED_IN = 'شما وارد حساب کاربری خود شدید!';
یه تغییری دادیم. ولی چون زیاد اشنا نیستیم یه مقدار گنگه برامون. بعدا بهتر میشیم

2022-07-28 07:16 UTC, Alirezab-2000 commented on src/app/pages/home/slideshow/slideshow.component.spec.ts
> -});
نه فایلشون پاک نشده. محتوای تست رو پاک کردیم. حالا نمیدونم گیت چرا همشو قرمز کرده.

2022-07-28 07:22 UTC, Alirezab-2000 commented on src/app/models/api/login.model.ts
> +}
پاکشون کردم

2022-07-28 07:23 UTC, ArefHbb approved these changes

2022-07-28 08:19 UTC, AliZoghi approved these changes

2022-07-28 09:08 UTC, ParsaArvanehPA requested changes

2022-07-28 09:08 UTC, ParsaArvanehPA commented on src/app/services/api/auth/auth.service.spec.ts
> +
del empty line

2022-07-28 09:08 UTC, ParsaArvanehPA commented on src/app/services/api/auth/auth.service.ts
> +        window.location.reload();
چرا به خط 37 نیاز هست؟

2022-07-28 09:24 UTC, AtaReversei commented on src/app/services/api/auth/auth.service.ts
> +        window.location.reload();
واسه اینکه اگه کاربر تو صفحه پروفایلش یا جای دیگه ای که بعد از خروج نباید اونجا باشه بود یه بار reload کنیم تا برگرده به صفحه اصلی

2022-07-28 09:55 UTC, ParsaArvanehPA approved these changes

2022-07-30 10:00 UTC, BijanEisapour approved these changes

2022-07-30 16:50 UTC, AtaReversei commented on src/app/app.component.ts
> +    public async checkIsLogin(): Promise<void> {
اصلاح شد

2022-07-30 16:53 UTC, Alirezab-2000 approved these changes

2022-07-30 16:54 UTC, merged