Phase09 test
Star-Academy/Summer1401-FE-Team03 pull request #4
Opened 2022-08-01 18:12 UTC by Alirezab-2000

2022-08-01 19:34 UTC, dibaaamir requested changes

2022-08-01 19:34 UTC, dibaaamir commented on src/app/components/card/card.component.scss
> +    width: 27rem;
logical

2022-08-01 19:34 UTC, dibaaamir commented on src/app/components/card/card.component.scss
>          width: 100%;
logical

2022-08-01 19:34 UTC, dibaaamir commented on src/app/components/card/card.component.spec.ts
> +    // it('should render - default src', () => {
delete comment

2022-08-01 19:34 UTC, dibaaamir commented on src/app/components/footer/footer.component.scss
>                      direction: ltr;
نمیدونم روش بهتره یا نه ولی اینو شاید بهتر باشه توی html بزارین

2022-08-01 19:34 UTC, dibaaamir commented on src/app/pages/home/component/cards/cards.component.scss
> +        width: 15%;
logical

2022-08-01 19:34 UTC, dibaaamir commented on src/app/pages/auth/register/register.component.html
> +        <input type="text" name="username" [(ngModel)]="user.username" />
required و بقیه مهما

2022-08-01 19:42 UTC, dorrin-sot requested changes

2022-08-01 19:42 UTC, dorrin-sot commented on src/app/pages/home/component/cards/cards.component.scss
> +        height: 3rem;
logical

2022-08-01 19:42 UTC, dorrin-sot commented on src/app/pages/home/component/cards/cards.component.spec.ts
> +    // }));
کامنت و حذف کنین

2022-08-01 20:40 UTC, dibaaamir approved these changes

2022-08-01 20:51 UTC, dorrin-sot requested changes

2022-08-01 20:51 UTC, dorrin-sot commented on src/app/components/header/component/header-profile-access/header-profile-access.component.spec.ts
> +        authService.isUserLoggedIn = true;
این تست و تست بعدی رو میتونید داخل for loop بزارید

2022-08-01 20:51 UTC, dorrin-sot commented on src/app/components/snackbar/snackbar.component.spec.ts
> +        debugger;
remove

2022-08-01 20:51 UTC, dorrin-sot commented on src/app/mock/authService.mock.ts
> +        console.log('login called');
console.log رو حذف کنید

2022-08-01 21:17 UTC, Alirezab-2000 commented on src/app/components/header/component/header-profile-access/header-profile-access.component.spec.ts
> +        authService.isUserLoggedIn = true;
این خط 43 رو عوض کردم و جاش متد های لاگین و لاگ اوت رو فراخوانی کردم. 
باقی خطوط هم یه متد ساختم و ریختمشون اونجا و توی تست از اون متد استفاده کردم

2022-08-01 21:18 UTC, Alirezab-2000 commented on src/app/components/snackbar/snackbar.component.spec.ts
> +        debugger;
اصلاح شد

2022-08-01 21:34 UTC, dorrin-sot approved these changes

2022-08-02 05:31 UTC, ParsaArvanehPA requested changes

2022-08-02 05:31 UTC, ParsaArvanehPA commented on src/app/components/card/card.component.spec.ts
> +    // defaults
کامنتت بی دلیله.
کی هست که کارما کرد کرده باشه و نیاز داره به اینی که نوشتی؟

2022-08-02 05:31 UTC, ParsaArvanehPA commented on src/app/components/card/card.component.spec.ts
> +    // tests
ن بابا!
اصلا مگه تو کارما بخش تست هم داریم :)

پاک

2022-08-02 05:31 UTC, ParsaArvanehPA commented on src/app/components/card/card.component.spec.ts
> +    // [SECTION] Utility Functions
هر تست ی بخش describe داره که باید تو اون بخش کاری که میخواد ذکر بشه رو بنویسی. اومدی این تسته fail شد. تو خود مرورگر که کسی که داره تست رو ران میکنه که نیمبینه این کامته رو

2022-08-02 05:31 UTC, ParsaArvanehPA commented on src/app/components/card/card.component.spec.ts
> +    function testDescription(description?: string): void {
دلیلی داره که arrow function نزدی؟
نکته خاصی ندارم سرش، فقط میخوام بدونم

2022-08-02 05:31 UTC, ParsaArvanehPA commented on src/app/components/divider-vertical/divider-vertical.component.spec.ts
> +    it('should render i', () => {
نام گذاری اشتباه

2022-08-02 05:31 UTC, ParsaArvanehPA commented on src/app/components/footer/footer.component.scss
> +                .t-number {
اینو قبلا هم ازتون ایارد گرفته بودم ولی باز برشگردونیدید!
نام گذاری اشتباه

2022-08-02 05:31 UTC, ParsaArvanehPA commented on src/app/components/header/component/header-profile-access/header-profile-access.component.spec.ts
> +    // utils functions
.

2022-08-02 05:31 UTC, ParsaArvanehPA commented on src/app/components/header/component/search-box/search-box.component.spec.ts
> +    it('should render i', () => {
گفتم

2022-08-02 05:31 UTC, ParsaArvanehPA commented on src/app/components/header/header.component.html
> +    <div title="لول کوین" *ngIf="authService.isUserLoggedIn" data-test-id="coin-box">
ی دیو داری کلا. نیازی نیست ک تغییر بدی اینو برای تستش

2022-08-02 05:31 UTC, ParsaArvanehPA commented on src/app/components/snackbar/services/snackbar/snackbar.service.ts
> +    private timeout?: ReturnType<typeof setTimeout>;
؟

2022-08-02 05:31 UTC, ParsaArvanehPA commented on src/app/components/snackbar/snackbar.component.spec.ts
> +    // util function
گفتم

2022-08-02 05:31 UTC, ParsaArvanehPA commented on src/app/pages/auth/register/register.component.html
> +        <input type="password" name="password" [(ngModel)]="user.password" required />
طرف الان از کجا باید بفهمه کدوما اجباری هستن کدوما اجباری نیست؟ 
منظور تا قبل از کلیک روی دکمه فرمه

2022-08-02 05:31 UTC, ParsaArvanehPA commented on src/app/pages/auth/register/register.component.spec.ts
> +    it('should change email value', () => {});
؟؟؟

2022-08-02 05:31 UTC, ParsaArvanehPA commented on src/app/pages/home/component/cards/cards.component.ts
> +            // behavior: 'smooth',
کامنت

2022-08-02 05:31 UTC, ParsaArvanehPA commented on src/app/pages/home/component/cards/cards.component.ts
> +            // behavior: 'smooth',
del

2022-08-02 05:31 UTC, ParsaArvanehPA commented on src/app/pages/home/component/cards/cards.component.ts
> +            // behavior: 'smooth',
del

2022-08-02 05:31 UTC, ParsaArvanehPA commented on src/app/pages/home/component/slideshow/slideshow.component.spec.ts
> +    // utils function
weqwda5sd4wqe+*/qwed10
6+das

2022-08-02 05:31 UTC, ParsaArvanehPA commented on src/app/pages/home/component/slideshow/slideshow.component.ts
> +    private interval?: ReturnType<typeof setInterval>;
?

2022-08-02 05:31 UTC, ParsaArvanehPA commented on src/app/services/api/auth/auth.service.spec.ts
> +    // utils function
..

2022-08-02 06:23 UTC, Alirezab-2000 commented on src/app/components/card/card.component.spec.ts
> +    // defaults
اصلاح شد

2022-08-02 06:23 UTC, Alirezab-2000 commented on src/app/components/card/card.component.spec.ts
> +    // tests
:))) اصلاح شد

2022-08-02 06:25 UTC, Alirezab-2000 commented on src/app/components/card/card.component.spec.ts
> +    // [SECTION] Utility Functions
البته این کامنت برای اینه که زیرش توابع کمکی رو نوشتیم. مربوط به تست خاصی نیست

2022-08-02 06:26 UTC, Alirezab-2000 commented on src/app/components/card/card.component.spec.ts
> +    function testDescription(description?: string): void {
نه. همینجوری با function شروع کردم. تست نیستن اینا البته. اینا توابعی هستن که تو تستا ازشون استفاده شده.

2022-08-02 06:28 UTC, Alirezab-2000 commented on src/app/components/divider-vertical/divider-vertical.component.spec.ts
> +    it('should render i', () => {
یه تغییری دادم اسمش رو

2022-08-02 06:29 UTC, Alirezab-2000 commented on src/app/components/footer/footer.component.scss
> +                .t-number {
اصلاح شد

2022-08-02 06:30 UTC, Alirezab-2000 commented on src/app/components/header/component/header-profile-access/header-profile-access.component.spec.ts
> +    // utils functions
اینارو زیرشون توابع کمکی نوشتیم. فکر میکنم بمونن بهتر باشه.

2022-08-02 06:31 UTC, Alirezab-2000 commented on src/app/components/header/component/search-box/search-box.component.spec.ts
> +    it('should render i', () => {
اصلاح شد

2022-08-02 06:33 UTC, Alirezab-2000 commented on src/app/components/header/header.component.html
> +    <div title="لول کوین" *ngIf="authService.isUserLoggedIn" data-test-id="coin-box">
اصلاح شد

2022-08-02 06:34 UTC, Alirezab-2000 commented on src/app/components/snackbar/services/snackbar/snackbar.service.ts
> +    private timeout?: ReturnType<typeof setTimeout>;
تو تایپ اسکریپت ایراد میگرفت. البته اشکالی ایجاد نمیکرد ولی گفتم اینجوری بنویسم ایراد نگیره

2022-08-02 06:43 UTC, Alirezab-2000 commented on src/app/pages/auth/register/register.component.spec.ts
> +    it('should change email value', () => {});
تلاش کردم یه تستی بنویسم ولی نشد. الان پاکش کردم

2022-08-02 06:44 UTC, Alirezab-2000 commented on src/app/pages/home/component/cards/cards.component.ts
> +            // behavior: 'smooth',
اصلاح شد

2022-08-02 06:46 UTC, Alirezab-2000 commented on src/app/pages/home/component/slideshow/slideshow.component.spec.ts
> +    // utils function
:)))) اخه حس میکنم بد  نیست باشن. ولی اگر فکر میکنی پاکشون کنم بهتره، مشکلی نیست پاکشون میکنم

2022-08-02 06:46 UTC, Alirezab-2000 commented on src/app/pages/home/component/slideshow/slideshow.component.ts
> +    private interval?: ReturnType<typeof setInterval>;
به همون دلیل بالا

2022-08-02 06:47 UTC, Alirezab-2000 commented on src/app/services/api/auth/auth.service.spec.ts
> +    // utils function
توضیح دادم

2022-08-02 07:58 UTC, SinaMAmini commented on src/app/components/snackbar/snackbar.component.spec.ts
> +});
بهتره snackbar به محض ورود به سایت به کاربر نشون داده نشه...
تجربه خوبی به کاربر نمیده

2022-08-02 07:58 UTC, SinaMAmini commented on src/app/pages/auth/login/login.component.html
> +        <input type="email" name="email" [(ngModel)]="user.email" required />
چرا برای ورود هم ایمیل داریم هم نام کاربری؟
مگه یه تناظر یک به یک بینشون نیست؟

2022-08-02 07:58 UTC, SinaMAmini commented on src/app/components/header/component/header-profile-access/header-profile-access.component.html
>          <i class="far fa-arrow-right-to-bracket"></i>
به نظرم بهتره یه کوچولو فاصله بین آیکون و ثبت نام باشه... خیلی چسبیدن...

2022-08-02 07:58 UTC, SinaMAmini commented on src/app/components/header/component/header-profile-access/header-profile-access.component.html
>  <popper-content #popperContent>
چرا توی این popper اسم hard code شده؟(چند خط بعد)
مگه از سرور نمیگیره؟

2022-08-02 07:58 UTC, SinaMAmini commented on src/app/components/footer/footer.component.html
>  </footer>
به نظرم بهتره کامپوننت footer و header ، سمت چپشون در یه خط فرضی تموم بشن...

2022-08-02 08:18 UTC, Negarnbkhti42 requested changes

2022-08-02 08:18 UTC, Negarnbkhti42 commented on src/app/pages/home/component/cards/cards.component.scss
> +        border-radius: 999rem;
با مقدار 50% هندل نمیشد؟

2022-08-02 08:21 UTC, Negarnbkhti42 commented
باگی دارید که در لحظه ورودی به صفحه احراز هویت، اسنک بارتون نشون داده میشه

2022-08-02 08:28 UTC, Negarnbkhti42 commented on src/app/components/header/header.component.spec.ts
> +        expect(element).not.toBeTruthy();
دلیلی داره که مستقیما از toBeFalsey استفاده نشده؟

2022-08-02 08:37 UTC, msrazavi requested changes

2022-08-02 08:37 UTC, msrazavi commented on src/app/components/footer/footer.component.html
> +            </li>
به نظرم زیر این‌ها خط نباشه قشنگ‌تره.

2022-08-02 08:37 UTC, msrazavi commented on src/app/pages/home/component/cards/cards.component.html
> +        <button (click)="scrollToRight()"><i class="far fa-angle-left"></i></button>
به نظرم این دکمه ها اگر دو طرف کارت‌ها باشن قشنگ‌تره.

2022-08-02 08:37 UTC, msrazavi commented on src/app/pages/home/component/cards/cards.component.html
> +        <button (click)="scrollToRight()"><i class="far fa-angle-left"></i></button>
با اسکرول به آخر سمت چپ هنوز fade هست انگار بازم ادامه داره ولی نمیره.

2022-08-02 08:37 UTC, msrazavi commented on src/app/pages/home/component/cards/cards.component.html
> +    <h2 class="title">بازی های مورد انتظار در سال جاری</h2>
نیم‌فاصله

2022-08-02 08:37 UTC, msrazavi commented on src/app/components/header/header.component.scss
>      width: 100%;
logical

2022-08-02 08:37 UTC, msrazavi commented on src/app/pages/auth/login/login.component.html
> +        <input type="password" name="password" [(ngModel)]="user.password" required />
به نظرم مرسوم نیست در ورود هم فیلد ایمیل باشه هم نام کاربری بعد یکیش ستاره دار باشه. میشه یه فیلد باشه «ایمیل یا نام کاربری»

2022-08-02 08:37 UTC, msrazavi commented on src/app/pages/home/component/slideshow/slideshow.component.ts
>          {src: 'assets/slides/03-compressed.webp', alt: 'بازی رد دد ریدمپشن دو'},
نیم‌فاصله

2022-08-02 08:37 UTC, msrazavi commented on src/app/pages/home/component/slideshow/slideshow.component.ts
>          {src: 'assets/slides/03-compressed.webp', alt: 'بازی رد دد ریدمپشن دو'},
اسم‌های انگلیسی رو انگلیسی بنویسید خواناتره.

2022-08-02 09:09 UTC, ParsaArvanehPA approved these changes

2022-08-02 09:14 UTC, Negarnbkhti42 requested changes

2022-08-02 09:14 UTC, Negarnbkhti42 commented on src/app/components/header/component/search-box/search-box.component.spec.ts
> +        expect(input?.type).toEqual('search');
میشه typecast به HTMLInput کرد

2022-08-02 09:59 UTC, Alirezab-2000 commented on src/app/components/snackbar/snackbar.component.spec.ts
> +});
بله ایرادش رو برطرف کردم

2022-08-02 10:03 UTC, Alirezab-2000 commented on src/app/components/header/component/header-profile-access/header-profile-access.component.html
>          <i class="far fa-arrow-right-to-bracket"></i>
اصلاح شد

2022-08-02 10:04 UTC, HessamCheraghi requested changes

2022-08-02 10:04 UTC, HessamCheraghi commented on src/app/pages/home/component/slideshow/slideshow.component.spec.ts
> +        }
اینجا بهتر نیست از متد `forEach` استفاده کنید؟
```JavaScript
children.forEach((_,i)=>{
        component.changeActiveIndex(i);

        fixture.detectChanges();

        let li = children[component.activeIndex];

        expect(li).toHaveClass('active');
})

2022-08-02 10:04 UTC, Alirezab-2000 commented on src/app/components/header/component/header-profile-access/header-profile-access.component.html
>  <popper-content #popperContent>
هنوز اون بخش رو تکمیل نکردیم ولی حتما انجام میدیم

2022-08-02 10:09 UTC, Alirezab-2000 commented on src/app/components/footer/footer.component.html
>  </footer>
اینطور هم هست درواقع. ولی به خاطر راست چین بودن متن. باعث شده فوتر کمی زودتر از header در سمت چپ به پایان برسه. ولی من با همگروهیم مطرح میکنم ببینم نظر ایشون چیه.

2022-08-02 10:09 UTC, Alirezab-2000 commented on src/app/pages/home/component/cards/cards.component.scss
> +        border-radius: 999rem;
یه مقداری دادیم دیگه در هر صورت دایره باشه. البته با چیزی که شما میگید هم درسته ولی فرق زیادی نمیکنه

2022-08-02 10:11 UTC, Alirezab-2000 commented on src/app/components/header/header.component.spec.ts
> +        expect(element).not.toBeTruthy();
اصلاح شد

2022-08-02 10:20 UTC, Alirezab-2000 commented on src/app/components/footer/footer.component.html
> +            </li>
بله مطرح میکنم با همگروهیم.

2022-08-02 10:31 UTC, SinaMAmini approved these changes

2022-08-02 10:58 UTC, Negarnbkhti42 commented on src/app/pages/auth/register/register.component.html
> +        <span class="required">کلمه عبور:</span>
میشه استایلش رو با شبه کلاس :required هم هندل کرد تا احتمال خطا کمتر بشه

2022-08-02 11:50 UTC, BijanEisapour requested changes
میخواهم => می‌خواهم
ثبت نام => ثبت‌نام
نام خانوادگی => نام‌خانوادگی
پرسش های => پرسش‌های
تخفیف ها => تخفیف‌ها
بازی های => بازی‌های
پنجه های => پنجه‌های
بازی ای => بازی‌ای

بقیشم خودت پیدا و درست کن

2022-08-02 11:50 UTC, BijanEisapour commented on src/app/components/header/component/header-profile-access/header-profile-access.component.spec.ts
> +    // utils functions
همه جا از یه نوشته استفاده کن
چرا متفاوتن؟

2022-08-02 11:50 UTC, BijanEisapour commented on src/app/components/header/component/header-profile-access/header-profile-access.component.spec.ts
> +        fixture.detectChanges();
چه خبره بابا؟
فقط قبل از expect یه بار detectChanges کن دیگه 

بعد چرا انقد Enter زدی؟

2022-08-02 11:50 UTC, BijanEisapour commented on src/app/components/header/component/search-box/search-box.component.spec.ts
> +    it('should have i tag with "far fa-magnifying-glass" class name ', () => {
اینجا صرفاً به‌صورت کلی بنویس چی رو تست میکنی 
فردا اگه کلاسش رو عوض کردی نیاز نباشه اینجا رو هم تغییر بدی

2022-08-02 11:50 UTC, BijanEisapour commented on src/app/components/header/header.component.spec.ts
> +    let authService: AuthServiceMock;
اسمش رو یه جوری بذار آدم بفهمه mock ئه

2022-08-02 11:50 UTC, BijanEisapour commented on src/app/components/snackbar/services/snackbar/snackbar.service.spec.ts
> +        service.show('test message', SnackbarTypes.Error);
نباید بعدش detectChanges بذاری؟

2022-08-02 11:50 UTC, BijanEisapour commented on src/app/components/snackbar/services/snackbar/snackbar.service.spec.ts
> +        service.snackbarCloseHandler();
نمیگم

2022-08-02 11:50 UTC, BijanEisapour commented on src/app/components/snackbar/services/snackbar/snackbar.service.spec.ts
> +    it('should disappear after 4000ms', fakeAsync(() => {
نمیگم

2022-08-02 11:50 UTC, BijanEisapour commented on src/app/components/snackbar/services/snackbar/snackbar.service.ts
> +    private timeout?: ReturnType<typeof setTimeout>;
چه ایرادی میگرفت؟

2022-08-02 11:50 UTC, BijanEisapour commented on src/app/guard/auth.guard.spec.ts
> +function mockRouterState(url: string): RouterStateSnapshot {
به نظر میرسه استفاده نشده

2022-08-02 11:50 UTC, BijanEisapour commented on src/app/mock/authService.mock.ts
> +        });
به جای این کار، متد رو async کن بعد از return معمولی استفاده کن

2022-08-02 11:50 UTC, BijanEisapour commented on src/app/pages/auth/login/login.component.spec.ts
> +    it('should change email value', () => {});
؟

2022-08-02 11:50 UTC, BijanEisapour commented on src/app/pages/home/component/cards/cards.component.ts
> +            left: this.outerContainer.nativeElement.scrollLeft + 294,
عدد لخت؟

2022-08-02 11:50 UTC, BijanEisapour commented on src/app/pages/home/component/cards/cards.component.ts
> +    public scrollToRight(): void {
خیلی شبیه متد بالاییه 
یکی شن یا یه متد private واسشون بذار

2022-08-02 11:50 UTC, BijanEisapour commented on src/app/pages/home/component/slideshow/slideshow.component.spec.ts
> +        let changeActiveIndexMethodSpy = spyOn(component, 'changeActiveIndex');
const

2022-08-02 11:50 UTC, BijanEisapour commented on src/app/pages/home/component/slideshow/slideshow.component.spec.ts
> +        let changeButtons = fixture.debugElement.queryAll(By.css('button'));
const

2022-08-02 11:50 UTC, BijanEisapour commented on src/app/pages/home/component/slideshow/slideshow.component.spec.ts
> +        for (let changeButton of changeButtons) {
const 
نمیگم

2022-08-02 11:50 UTC, BijanEisapour commented on src/app/pages/home/component/slideshow/slideshow.component.spec.ts
> +        expect(images.length).toEqual(TEST_IMAGES.length);
خیلی الکی enter میزنی

2022-08-02 11:50 UTC, BijanEisapour commented on src/app/pages/home/component/slideshow/slideshow.component.spec.ts
> +        }
نه بهتر نیست

2022-08-02 11:50 UTC, BijanEisapour commented on src/app/pages/home/component/slideshow/slideshow.component.spec.ts
> +    it('should change active index after 4000 milliseconds', fakeAsync(() => {
نمیگم

2022-08-02 11:50 UTC, BijanEisapour commented on src/app/services/api/auth/auth.service.spec.ts
> +        await service.register({username: 'bad ata', email: 'badata@gmail.com', password: ''});
:)

2022-08-02 11:50 UTC, BijanEisapour commented on .github/workflows/deploy.yml
> +            - name: Angular
404.html hack

2022-08-02 11:50 UTC, BijanEisapour commented on src/app/pages/home/component/slideshow/slideshow.component.ts
>          {src: 'assets/slides/01-compressed.webp', alt: 'بازی ویچر سه و اکسپنشن قلب های سنگی'},
اسم بازی‌ها باید انگلیسی باشه

2022-08-02 12:29 UTC, Alirezab-2000 commented on src/app/pages/home/component/cards/cards.component.html
> +        <button (click)="scrollToRight()"><i class="far fa-angle-left"></i></button>
حالا تصمیم این بوده که کنار هم بذاریمشون

2022-08-02 12:29 UTC, Alirezab-2000 commented on src/app/pages/home/component/cards/cards.component.html
> +        <button (click)="scrollToRight()"><i class="far fa-angle-left"></i></button>
حالا تصمیم این بوده که کنار هم بذاریمشون

2022-08-02 12:32 UTC, Alirezab-2000 commented on src/app/pages/home/component/cards/cards.component.html
> +        <button (click)="scrollToRight()"><i class="far fa-angle-left"></i></button>
این رو ما اینجوری هندل کردیم که یه مقدار کارت اخر از سمت چپ فاصله میگیره تا fade دیده نشه. در اینده میخوایم یه کامپوننتی هم  سمت چپ بذاریم که به عنوان موارد بیشتر باشه. بعد از کارت اخر. و احتمالا اونموقع fade رو حذف کنیم

2022-08-02 12:53 UTC, Alirezab-2000 commented on src/app/pages/home/component/cards/cards.component.html
> +    <h2 class="title">بازی های مورد انتظار در سال جاری</h2>
حل شد

2022-08-02 12:54 UTC, Alirezab-2000 commented on src/app/components/header/header.component.scss
>      width: 100%;
حل شد

2022-08-02 12:57 UTC, Alirezab-2000 commented on src/app/pages/auth/login/login.component.html
> +        <input type="password" name="password" [(ngModel)]="user.password" required />
بله در ادامه قراره ایمیل رو حذف کنیم کلا

2022-08-02 12:57 UTC, Alirezab-2000 commented on src/app/pages/home/component/slideshow/slideshow.component.ts
>          {src: 'assets/slides/03-compressed.webp', alt: 'بازی رد دد ریدمپشن دو'},
حل شد

2022-08-02 12:58 UTC, Alirezab-2000 commented on src/app/pages/home/component/slideshow/slideshow.component.ts
>          {src: 'assets/slides/03-compressed.webp', alt: 'بازی رد دد ریدمپشن دو'},
بله تصویر ها. از سرور قراره بیان. ما همینجوری اینا رو گذاشتیم. عوض میشن حتما

2022-08-02 13:48 UTC, Alirezab-2000 commented on src/app/components/header/component/header-profile-access/header-profile-access.component.spec.ts
> +import {AuthServiceMock} from '../../../../mock/authService.mock';
بله در نظر داریم در ادامه اصلاحش کنیم

2022-08-02 13:49 UTC, Alirezab-2000 commented on src/app/guard/auth.guard.spec.ts
> +        });
یه جور گروه بندی تست هاست. نه مشکلی ایجاد نمیکنه

2022-08-02 13:50 UTC, Alirezab-2000 commented on src/app/pages/auth/register/register.component.spec.ts
> +import {SnackbarService} from '../../../components/snackbar/services/snackbar/snackbar.service';
بله. این سرویس فقط اینجا استفاده میشد. ما داخل پوشه snackbar یه پوشه سرویس درست کردیم و سرویس مربوط بهش رو گذاشتیم داخلش.  طبق توصیه منتور ها

2022-08-02 13:53 UTC, Alirezab-2000 commented on src/app/pages/home/component/cards/cards.component.spec.ts
> +        let appCards = fixture.debugElement.queryAll(By.css('app-card'));
حل شد

2022-08-02 13:53 UTC, Alirezab-2000 commented on src/app/pages/auth/register/register.component.spec.ts
> +        let registerMethodSpy = spyOn(authService, 'register');
حل شد

2022-08-02 13:54 UTC, Alirezab-2000 commented on src/app/pages/auth/register/register.component.html
> +        <span class="required">کلمه عبور:</span>
بله. چون میخواستیم به span استایل بدیم. یه ذره سعی کردیم با input بهش برسیم بعد که دیدیم نشد دیگه این راه رو انتخاب کردیم که زیاد وقت نذاریم

2022-08-02 14:42 UTC, Negarnbkhti42 approved these changes

2022-08-02 16:02 UTC, Alirezab-2000 commented on src/app/components/header/component/header-profile-access/header-profile-access.component.spec.ts
> +    // utils functions
حل شد

2022-08-02 16:04 UTC, Alirezab-2000 commented on src/app/components/header/component/header-profile-access/header-profile-access.component.spec.ts
> +        fixture.detectChanges();
حل شد. گفتم بین بخش های مختلف فاصله باید باشه

2022-08-02 16:08 UTC, Alirezab-2000 commented on src/app/components/header/header.component.spec.ts
> +    let authService: AuthServiceMock;
حل شد

2022-08-02 16:09 UTC, Alirezab-2000 commented on src/app/components/snackbar/services/snackbar/snackbar.service.spec.ts
> +        service.show('test message', SnackbarTypes.Error);
نه مشکلی نیست پاس میشه

2022-08-02 16:10 UTC, Alirezab-2000 commented on src/app/components/snackbar/services/snackbar/snackbar.service.spec.ts
> +        service.snackbarCloseHandler();
مشکلی ایجاد نمیکنه. شاید به خاطر اینه چون snackbar ما با چیزی که تو توی کارگاه نوشتی فرق داره یه مقدار. ما همه متدا رو بردیم تو سرویس

2022-08-02 16:11 UTC, Alirezab-2000 commented on src/app/components/snackbar/services/snackbar/snackbar.service.spec.ts
> +    it('should disappear after 4000ms', fakeAsync(() => {
اینم به نظرم باید 4000 میلی ثانیه باشه. نباید عوض شه به خاطر همین اینجوری گذاشتم توضیحاتش رو. اگر منظورت رو درست فهمیده باشم

2022-08-02 16:12 UTC, Alirezab-2000 commented on src/app/components/snackbar/services/snackbar/snackbar.service.ts
> +    private timeout?: ReturnType<typeof setTimeout>;
میگفت Timeout نمیتونه به number نسبت داده بشه

2022-08-02 16:13 UTC, Alirezab-2000 commented on src/app/guard/auth.guard.spec.ts
> +function mockRouterState(url: string): RouterStateSnapshot {
اره پاکش کردم

2022-08-02 16:13 UTC, Alirezab-2000 commented on src/app/mock/authService.mock.ts
> +        });
حل شد

2022-08-02 16:14 UTC, Alirezab-2000 commented on src/app/pages/auth/login/login.component.spec.ts
> +    it('should change email value', () => {});
پاک شد

2022-08-02 16:16 UTC, Alirezab-2000 commented on src/app/pages/home/component/cards/cards.component.ts
> +            left: this.outerContainer.nativeElement.scrollLeft + 294,
حل شد

2022-08-02 16:20 UTC, Alirezab-2000 commented on src/app/pages/home/component/cards/cards.component.ts
> +    public scrollToRight(): void {
حل شد

2022-08-02 16:22 UTC, Alirezab-2000 commented on src/app/pages/home/component/slideshow/slideshow.component.spec.ts
> +        let changeActiveIndexMethodSpy = spyOn(component, 'changeActiveIndex');
حل شد

2022-08-02 16:23 UTC, Alirezab-2000 commented on src/app/pages/home/component/slideshow/slideshow.component.spec.ts
> +        let changeButtons = fixture.debugElement.queryAll(By.css('button'));
حل شد

2022-08-02 16:24 UTC, Alirezab-2000 commented on src/app/pages/home/component/slideshow/slideshow.component.spec.ts
> +        for (let changeButton of changeButtons) {
حل شد

2022-08-02 16:25 UTC, Alirezab-2000 commented on src/app/pages/home/component/slideshow/slideshow.component.spec.ts
> +        expect(images.length).toEqual(TEST_IMAGES.length);
بخش های جدان. ولی حالا یه مقدار پاکشون کردم

2022-08-02 16:25 UTC, Alirezab-2000 commented on src/app/pages/home/component/slideshow/slideshow.component.spec.ts
> +    it('should change active index after 4000 milliseconds', fakeAsync(() => {
این 4000 به نظرم ثابت باشه بهتره. اگر طرف عوضش کرد ارور بده

2022-08-02 16:28 UTC, Alirezab-2000 commented on .github/workflows/deploy.yml
> +            - name: Angular
گذاشته شد

2022-08-02 16:30 UTC, Alirezab-2000 commented on src/app/pages/home/component/slideshow/slideshow.component.ts
>          {src: 'assets/slides/01-compressed.webp', alt: 'بازی ویچر سه و اکسپنشن قلب های سنگی'},
انجام شد

2022-08-02 16:31 UTC, Alirezab-2000 commented on src/app/services/api/auth/auth.service.spec.ts
> +        await service.register({username: 'bad ata', email: 'badata@gmail.com', password: ''});
هیسسس هیچی نگو :))

2022-08-02 17:54 UTC, msrazavi approved these changes

2022-08-03 04:38 UTC, HessamCheraghi approved these changes

2022-08-06 14:17 UTC, BijanEisapour approved these changes

2022-08-07 14:41 UTC, merged